import { sidebar } from "vuepress-theme-hope";

export const enSidebar = sidebar({
  "/": [
    { text: "tldr: What is Gyroscope", link: "/", icon: "", collapsible: false },
    { text: "Audit Reports", link: "/audit-reports.md", icon: "", collapsible: false },
    {
      text: "POOLS",
      icon: "",
      collapsible: true,
      children: [
        { text: "Overview", link: "/pools/concentrated-liquidity-pools.md" },
        { text: "2-CLPs", link: "/pools/2-clps.md" },
        { text: "3-CLPs", link: "/pools/3-clps.md" },
        { text: "E-CLPs", link: "/pools/e-clps.md" },
        { text: "Dynamic CLPs", link: "/pools/dynamic-clps.md" },
        { text: "Rehype CLPs", link: "/pools/rehype-clps.md" },
        { text: "Technical documents", link: "/pools/technical-documents.md" },
      ],
    },
    {
      text: "Governance",
      icon: "",
      collapsible: true,
      children: [
        { text: "Overview", link: "/governance/overview.md" },
        {
          text: "How it works",
          link: "/governance/how-it-works/README.md",
          collapsible: true,
          children: [
            { text: "Voting Vaults", link: "/governance/how-it-works/voting-vaults/README.md" },
            { text: "The Founding Member Vault", link: "/governance/how-it-works/voting-vaults/the-founding-member-vault.md" },
            { text: "Councillor Vault", link: "/governance/how-it-works/voting-vaults/councillor-vault.md" },
            { text: "Associated DAO Vault", link: "/governance/how-it-works/voting-vaults/associated-dao-vault.md" },
            { text: "GYD LP Vault", link: "/governance/how-it-works/voting-vaults/gyd-lp-vault.md" },
            { text: "GYFI Vault", link: "/governance/how-it-works/voting-vaults/gyfi-vault.md" },
            { text: "Action Tiering", link: "/governance/how-it-works/action-tiering.md" },
            { text: "On-chain proposals", link: "/governance/how-it-works/on-chain-proposals.md" },
            { text: "Vote delegation", link: "/governance/how-it-works/vote-delegation.md" },
            { text: "Conditional cashflows", link: "/governance/how-it-works/conditional-cashflows.md" },
            { text: "GYD Recovery Module", link: "/governance/how-it-works/gyd-recovery-module.md" },
            {
              text: "Optimistic Approval",
              link: "/governance/how-it-works/optimistic-approval/README.md",
              collapsible: true,
              children: [
                { text: "Emergency Recovery", link: "/governance/how-it-works/optimistic-approval/emergency-recovery.md" },
                { text: "Limiting Upgradeability", link: "/governance/how-it-works/optimistic-approval/limiting-upgradeability.md" },
              ],
            },
          ],
        },
        { text: "Governance process", link: "/governance/governance-process.md" },
        {
          text: "GYFI Tokenomics",
          link: "/governance/gyfi-tokenomics/README.md",
          collapsible: true,
          children: [
            { text: "Token Allocation", link: "/governance/gyfi-tokenomics/token-allocation.md" },
            { text: "Release schedules", link: "/governance/gyfi-tokenomics/release-schedules.md" },
            { text: "Eligibility", link: "/governance/gyfi-tokenomics/eligibility.md" },
          ],
        },
      ],
    },
    {
      text: "GYD",
      icon: "",
      collapsible: true,
      children: [
        { text: "Overview", link: "/gyd/readme.md" },
        {
          text: "How it works",
          link: "/gyd/how-it-works/README.md",
          collapsible: true,
          children: [
            { text: "Reserve design", link: "/gyd/how-it-works/reserve.md" },
            {
              text: "Autonomous pricing",
              link: "/gyd/how-it-works/autonomous-pricing/README.md",
              collapsible: true,
              children: [
                { text: "Dynamic Stability Mechanism", link: "/gyd/how-it-works/autonomous-pricing/pamm.md" },
                { text: "GYD Trading Pools", link: "/gyd/how-it-works/autonomous-pricing/samm.md" },
                { text: "Economic intuition", link: "/gyd/how-it-works/autonomous-pricing/economic-intuition.md" },
              ],
            },
            { text: "Reserve Safety Checks", link: "/gyd/how-it-works/reserve-safety-checks.md" },
            { text: "Complementary stability mechanisms", link: "/gyd/how-it-works/gyroscope-stability.md" },
            {
              text: "Oracles & price feeds",
              link: "/gyd/how-it-works/oracles/README.md",
              collapsible: true,
              children: [
                { text: "Consolidated price feed", link: "/gyd/how-it-works/oracles/consolidated-price-feed.md" },
                { text: "LP share pricing", link: "/gyd/how-it-works/oracles/lp-share-pricing.md" },
              ],
            },
            { text: "Risks", link: "/gyd/how-it-works/risks.md" },
            { text: "DSM error codes", link: "/gyd/how-it-works/dsm-error-codes.md" },
            { text: "Protocol fees", link: "/gyd/how-it-works/protocol-fees.md" },
          ],
        },
        {
          text: "sGYD",
          link: "/gyd/sgyd/README.md",
          collapsible: true,
          children: [
            { text: "Yield Emission Process", link: "/gyd/sgyd/yield-emission-process.md" },
            { text: "Security", link: "/gyd/sgyd/security.md" },
            { text: "Audit Report", link: "/gyd/sgyd/audit-report.md" },
            { text: "Code Repositories", link: "/gyd/sgyd/code-repositories.md" },
            { text: "Contract Addresses", link: "/gyd/sgyd/contract-addresses.md" },
            { text: "Supported Venues", link: "/gyd/sgyd/supported-venues.md" },
            { text: "sGYD Internals", link: "/gyd/sgyd/sgyd-internals.md" },
            { text: "Risks", link: "/gyd/sgyd/risks.md" },
          ],
        },
        { text: "Technical Documents", link: "/gyd/technical-documents.md" },
      ],
    },
    {
      text: "Deployed Contracts",
      icon: "",
      collapsible: true,
      children: [
        {
          text: "Contract addresses",
          link: "/deployed-contracts/contract-addresses/README.md",
          collapsible: true,
          children: [
            { text: "Bridged GYD", link: "/deployed-contracts/contract-addresses/bridged-gyd.md" },
            { text: "GYFI", link: "/deployed-contracts/contract-addresses/gyfi.md" },
            { text: "Pools", link: "/deployed-contracts/contract-addresses/pools.md" },
            { text: "GYD Core", link: "/deployed-contracts/contract-addresses/gyd-core.md" },
            {
              text: "Governance",
              link: "/deployed-contracts/contract-addresses/governance/README.md",
              collapsible: true,
              children: [
                { text: "L1 Governance", link: "/deployed-contracts/contract-addresses/governance/l1-governance.md" },
                { text: "L2 Governance", link: "/deployed-contracts/contract-addresses/governance/l2-governance.md" },
              ],
            },
            { text: "Gyro Proto", link: "/deployed-contracts/contract-addresses/contract-addresses.md" },
            { text: "Consolidated price feed", link: "/deployed-contracts/contract-addresses/consolidated-price-feed.md" },
          ],
        },
      ],
    },
    { text: "Official channels", link: "/official-channels.md", icon: "", collapsible: false },
    {
      text: "FAQ",
      link: "/faq/README.md",
      collapsible: true,
      children: [
        { text: "Coinmarketcap", link: "/faq/coinmarketcap.md" },
        { text: "Is there info on the Gamified Testnet?", link: "/faq/is-there-info-on-the-gamified-testnet.md" },
        { text: "Is there a Gyroscope whitepaper?", link: "/faq/is-there-a-gyroscope-whitepaper.md" },
        { text: "How is Gyroscope different?", link: "/faq/how-is-gyroscope-different.md" },
        { text: "Why is it called Gyroscope?", link: "/faq/why-is-it-called-gyroscope.md" },
        { text: "How scalable is Gyroscope?", link: "/faq/soundly-scalable.md" },
        { text: "What are use cases of Gyroscope?", link: "/faq/gyroscope-use-cases.md" },
        { text: "Gyroscope & Academia", link: "/faq/research.md" },
        { text: "Classical FAQ", link: "/faq/classical-faq.md" },
        { text: "Coingecko", link: "/faq/coingecko.md" },
      ],
    },
    { text: "Press kit", link: "/press-kit.md", icon: "", collapsible: false },
    { text: "Learn more", link: "/learn-more.md", icon: "", collapsible: false },
    { text: "Licensing", link: "/licensing.md", icon: "", collapsible: false },
  ],
});